# Generated by Django 4.2.4 on 2023-08-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=100)),
                ('carrer', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=20)),
            ],
        ),
    ]
