# Generated by Django 4.2.4 on 2023-08-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='surnames',
            field=models.CharField(default='true', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(max_length=100),
        ),
    ]
